### ISSUE TITLE
gasmask crash in macOs Sierra(10.12)

### ISSUE THREAD

**Issue by Shangshj** [2ndalpha/gasmask#103] opened 2016-09-24 03:15 UTC

**Comment by jwsky** [comment] 2016-09-26 07:43
Me too. Really looking forward to see the issue fixed soon as this OS has been online for half a month, thank you so much.

**Comment by 2ndalpha** [comment] 2016-09-26 07:44
Duplicate of #100

**Closed by 2ndalpha** 2016-09-26 07:44 UTC

**Comment by zxl20zxl** [comment] 2016-10-20 06:28
1 plus
